export const FIELD_LABELS = {
  collection: {
    platform: "采集平台", mode: "采集方式", encrypt_expect_id: "推荐流期望 ID",
    keywords: "搜索关键词", cities: "城市", city: "城市",
    city_code: "城市编码", max_pages: "每组最多页数", target_jobs: "本轮目标采集数",
    sort: "搜索排序", daily_search_page_limit: "每日列表页上限",
    daily_detail_page_limit: "每日详情页上限",
    max_consecutive_page_failures: "连续页面失败上限",
    risk_pause_min_minutes: "风险暂停最短分钟数",
    risk_pause_max_minutes: "风险暂停最长分钟数",
    collection_delay_multiplier: "采集等待倍率",
    boss_salary_decode_failure: "薪资解码失败时",
  },
  profile: {
    resume_path: "简历文本路径", education: "学历", experience_filters: "工作年限",
    company_sizes: "公司规模", recruitment_types: "招聘类型",
    salary_min: "期望月薪下限（K）", salary_max: "期望月薪上限（K）",
    filter_unparsed_salary: "过滤面议或无法解析薪资",
    deal_breakers: "岗位名称排除词", jd_deal_breakers: "JD 排除词",
    blocked_companies: "公司排除词", exclude_headhunter: "排除猎头",
  },
  ai: {
    use_ai_score: "启用 AI 评分", use_ai_greeting: "自动生成招呼语",
    score_user_prompt: "评分补充要求", greeting_user_prompt: "招呼语补充提示词模板",
    greeting_template: "固定招呼语模板",
    score_threshold: "评分门槛",
    provider: "API 协议", service: "服务商", model: "模型",
    base_url: "API 地址",
    thinking: "思考模式", thinking_budget: "思考预算",
    timeout_seconds: "单次请求超时（秒）", retry_count: "额外重试次数",
    retry_delay_min_seconds: "重试最短等待（秒）",
    retry_delay_max_seconds: "重试最长等待（秒）",
    ai_api_concurrency: "最大并发请求数",
  },
  browser: { cdp_url: "Chrome 调试地址" },
  safety: {
    daily_platform_page_limit: "每日平台总页面上限",
    risk_lock_minutes: "风险锁定分钟数", state_db: "SQLite 数据库路径",
  },
  monitoring: {
    message_limit: "每条会话消息数",
    followup_enabled: "启用追问", followup_days: "扫描最近活动天数",
    followup_unread: "追问未读招呼", followup_read_no_reply: "追问已读未回招呼",
    followup_cooldown_hours: "追问冷却时长（小时）",
    followup_max_count: "每条会话最多追问次数",
    filter_review_required: "删除前人工审核",
  },
};

export const FIELD_HELP = {
  "collection.encrypt_expect_id": "推荐流必填；输入 ID 后按空格添加。搜索流须留空。",
  "collection.keywords": "搜索流必填；输入关键词后按空格添加。推荐流须留空。",
  "collection.target_jobs": "达到预筛通过数后停止；启用 AI 评分时，须同时达到评分门槛。",
  "collection.max_pages": "每轮每个期望 ID 或城市与关键词组合最多读取的页数。",
  "collection.cities": "可多选；不选则按 BOSS 当前会话的城市搜索，城市编码自动匹配。",
  "collection.city": "留空表示不指定城市，由 BOSS 当前会话决定范围。",
  "collection.city_code": "城市未在内置映射中时填写。",
  "collection.collection_delay_multiplier": "1～5；数值越大，采集间隔越长。",
  "profile.education": "按空格添加；留空表示不限。可用：学历不限、初中及以下、中专/中技、高中、大专、本科、硕士、博士。",
  "profile.experience_filters": "按空格添加；留空表示不限。可用：经验不限、应届生、在校生、1年内、1-3、3-5、5-10、10年以上。",
  "profile.company_sizes": "按空格添加；留空表示不限。可用：0-20人、20-99人、100-499人、500-999人、1000-9999人、10000人以上。",
  "profile.recruitment_types": "按空格添加；输入社招、校招或实习。",
  "profile.salary_min": "0 表示不限制下限。",
  "profile.salary_max": "0 表示不限制上限。",
  "profile.deal_breakers": "按空格添加排除词；英文不区分大小写。",
  "profile.jd_deal_breakers": "按空格添加 JD 排除词。",
  "profile.blocked_companies": "按空格添加公司排除词。",
  "ai.use_ai_greeting": "需要同时开启 AI 评分；只为达到评分门槛的岗位生成。",
  "ai.greeting_user_prompt": "选填；自动生成和岗位详情中点击 AI 生成时都会使用。留空则使用默认生成规则。",
  "ai.greeting_template": "选填；采集时填入符合条件的岗位，发送前仍可编辑。最多 300 字，留空则手动填写。",
  "ai.ai_api_concurrency": "线程池在服务启动时建立；点击生效配置后会自动重启 API 服务。",
  "safety.state_db": "点击生效配置后会自动重启 API 服务并使用新数据库。",
  "monitoring.followup_days": "只扫描「仅沟通」中最近 X 天有活动的会话。",
  "monitoring.followup_types": "可多选未读、已读未回；不选则不生成追问。",
  "monitoring.followup_cooldown_hours": "第一次从招呼语发送时间起算，以后从上次追问发送时间起算。",
  "monitoring.filter_review_required": "「新招呼」公司名命中岗位预筛中的公司排除词时生成删除候选。关闭审核后会自动删除；扫描不会打开会话。",
};

export const FIELD_OPTIONS = {
  "collection.platform": [["boss", "BOSS"]],
  "collection.mode": [["recommend", "推荐流"], ["search", "搜索流"]],
  "collection.sort": [["default", "默认"], ["newest", "最新"]],
  "collection.boss_salary_decode_failure": [["stop", "停止采集"], ["skip_job", "跳过该岗位"]],
  "ai.thinking": [["auto", "自动"], ["enabled", "开启"], ["disabled", "关闭"]],
};

export const RESTART_FIELDS = new Set([
  "ai.ai_api_concurrency", "safety.state_db",
]);
